######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 7 11:54:42 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += connections_window.h emct.h emct_main.h
FORMS += Connection_UI.ui EMCTUI_Prop2.ui
SOURCES += connections_window.cpp emct_main.cpp main.cpp
