#############################################################################
# Makefile for building: EMCT
# Generated by qmake (2.01a) (Qt 4.6.2) on: Thu Jul 7 11:54:46 2011
# Project:  EMCT.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile EMCT.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = connections_window.cpp \
		emct_main.cpp \
		main.cpp moc_connections_window.cpp \
		moc_emct_main.cpp
OBJECTS       = connections_window.o \
		emct_main.o \
		main.o \
		moc_connections_window.o \
		moc_emct_main.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		EMCT.pro
QMAKE_TARGET  = EMCT
DESTDIR       = 
TARGET        = EMCT

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_Connection_UI.h ui_EMCTUI_Prop2.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EMCT.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile EMCT.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile EMCT.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/EMCT1.0.0 || $(MKDIR) .tmp/EMCT1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/EMCT1.0.0/ && $(COPY_FILE) --parents connections_window.h emct.h emct_main.h .tmp/EMCT1.0.0/ && $(COPY_FILE) --parents connections_window.cpp emct_main.cpp main.cpp .tmp/EMCT1.0.0/ && $(COPY_FILE) --parents Connection_UI.ui EMCTUI_Prop2.ui .tmp/EMCT1.0.0/ && (cd `dirname .tmp/EMCT1.0.0` && $(TAR) EMCT1.0.0.tar EMCT1.0.0 && $(COMPRESS) EMCT1.0.0.tar) && $(MOVE) `dirname .tmp/EMCT1.0.0`/EMCT1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/EMCT1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_connections_window.cpp moc_emct_main.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_connections_window.cpp moc_emct_main.cpp
moc_connections_window.cpp: ui_Connection_UI.h \
		emct_main.h \
		ui_EMCTUI_Prop2.h \
		emct.h \
		connections_window.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) connections_window.h -o moc_connections_window.cpp

moc_emct_main.cpp: ui_EMCTUI_Prop2.h \
		emct.h \
		emct_main.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) emct_main.h -o moc_emct_main.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_Connection_UI.h ui_EMCTUI_Prop2.h
compiler_uic_clean:
	-$(DEL_FILE) ui_Connection_UI.h ui_EMCTUI_Prop2.h
ui_Connection_UI.h: Connection_UI.ui
	/usr/bin/uic-qt4 Connection_UI.ui -o ui_Connection_UI.h

ui_EMCTUI_Prop2.h: EMCTUI_Prop2.ui
	/usr/bin/uic-qt4 EMCTUI_Prop2.ui -o ui_EMCTUI_Prop2.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

connections_window.o: connections_window.cpp emct_main.h \
		ui_EMCTUI_Prop2.h \
		emct.h \
		connections_window.h \
		ui_Connection_UI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connections_window.o connections_window.cpp

emct_main.o: emct_main.cpp emct_main.h \
		ui_EMCTUI_Prop2.h \
		emct.h \
		connections_window.h \
		ui_Connection_UI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o emct_main.o emct_main.cpp

main.o: main.cpp emct.h \
		emct_main.h \
		ui_EMCTUI_Prop2.h \
		connections_window.h \
		ui_Connection_UI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_connections_window.o: moc_connections_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connections_window.o moc_connections_window.cpp

moc_emct_main.o: moc_emct_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_emct_main.o moc_emct_main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

